config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :jobs
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Simple forum discussion
  mount SimpleDiscussion::Engine => "/forum"

  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :integer          default("contract")
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  featured_until      :datetime
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  slug                :string
#  status              :integer          default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_slug     (slug) UNIQUE
#  index_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  # Friendly
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Richtext
  has_rich_text :description
  has_rich_text :company_description

  # ActiveStorage
  has_one_attached :company_logo

  # Association
  belongs_to :user

  # Define status of job using enum
  enum status: { pending: 0, published: 1, archived: 2 }

  # Define compensation type of job using enum
  enum compensation_type: { contract: 0, fulltime: 1 }

  def should_generate_new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  developer              :boolean          default(FALSE)
#  email                  :string           default(""), not null
#  employer               :boolean          default(FALSE)
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  moderator              :boolean
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  slug                   :string
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_slug                  (slug) UNIQUE
#
class User < ApplicationRecord
  # Add simple forum discussio
  include SimpleDiscussion::ForumUser

  # Friendly
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Name of user
  has_person_name

  # Association
  has_many :jobs, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def name
    "#{first_name} #{last_name}"
  end

  def should_generate_new_friendly_id?
    if !slug?
      first_name_changed? || last_name_changed?
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    keys = %i[name developer employer]
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
    devise_parameter_sanitizer.permit(:account_update, keys: keys)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @jobs = Job.all
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_job
    @job = Job.friendly.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:company_website, :compensation_range, :compensation_type, :estimated_hours,
                                :headquarters, :link_to_apply, :price, :remote, :title, :upsell_type, :years_of_experience)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, styles: "fill-current text-gray-500", title: nil)
    filename = "#{name.svg}"
    title  ||= name.underscore.humanize
    inline_svg_tag(filename, aria: true, nocomment: true, title: title, class: styles)
  end

  def admin?
    user_signed_in? && current_user.admin?
  end

  def author_of(resource)
    user_signed_in? && current_user.id == resource.user_id
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/simple_discussion/forum_posts_helper.rb
module SimpleDiscussion::ForumPostsHelper
  # Override this to use avatars from other places than Gravatar
  def avatar_tag(email)
    gravatar_image_tag(email, gravatar: { size: 40 }, class: "rounded avatar")
  end

  def category_link(category)
    link_to category.name, simple_discussion.forum_category_forum_threads_path(category),
      style: "color: #{category.color}"
  end

  # Override this method to provide your own content formatting like Markdown
  def formatted_content(text)
    simple_format(text)
  end

  def forum_post_classes(forum_post)
    klasses = ["forum-post", "card", "mb-3"]
    klasses << "solved" if forum_post.solved?
    klasses << "original-poster" if forum_post.user == @forum_thread.user
    klasses
  end

  def forum_user_badge(user)
    if user.respond_to?(:moderator) && user.moderator?
      content_tag :span, "Mod", class: "badge badge-default"
    end
  end
end

app/helpers/simple_discussion/forum_threads_helper.rb
module SimpleDiscussion::ForumThreadsHelper
  # Used for flagging links in the navbar as active
  def forum_link_to(path, opts={}, &block)
    link_to path, class: forum_link_class(path, opts), &block
  end

  def forum_link_class(matches, opts={})
    case matches
    when Array
      "active" if matches.any?{ |m| request.path.starts_with?(m) }
    when String
      "active" if opts.fetch(:exact, false) ? request.path == matches : request.path.starts_with?(matches)
    end
  end

  # A nice hack to manipulate the layout so we can have sub-layouts
  # without any changes in the user's application.
  #
  # We use this for rendering the sidebar layout for all the forum pages
  #
  # https://mattbrictson.com/easier-nested-layouts-in-rails
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(file: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<div class="max-w-lg mx-auto mt-16 text-center">
  <h2 class="mb-4 text-3xl font-black">Welcome to railsdevs</h2>
  <p class="text-lg leading-snug">Use this starting point as a way to quickly find a Ruby on Rails job.</p>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link_to_apply %>
    <%= form.text_field :link_to_apply %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :company_website %>
    <%= form.text_field :company_website %>
  </div>

  <div class="field">
    <%= form.label :company_description %>
    <%= form.rich_text_area :company_description %>
  </div>

  <div class="field">
    <%= form.label :role_type %>
    <%= form.text_field :role_type %>
  </div>

  <div class="field">
    <%= form.label :compensation_range %>
    <%= form.text_field :compensation_range %>
  </div>

  <div class="field">
    <%= form.label :remote %>
    <%= form.check_box :remote %>
  </div>

  <div class="field">
    <%= form.label :years_of_experience %>
    <%= form.text_field :years_of_experience %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link to apply</th>
      <th>Description</th>
      <th>Company name</th>
      <th>Company website</th>
      <th>Company description</th>
      <th>Compensation range</th>
      <th>Remote</th>
      <th>Years of experience</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.link_to_apply %></td>
        <td><%= job.description %></td>
        <td><%= job.company_name %></td>
        <td><%= job.company_website %></td>
        <td><%= job.company_description %></td>
        <td><%= job.compensation_range %></td>
        <td><%= job.remote %></td>
        <td><%= job.years_of_experience %></td>
        <td><%= job.user_id %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Link to apply:</strong>
  <%= @job.link_to_apply %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @job.company_name %>
</p>

<p>
  <strong>Company website:</strong>
  <%= @job.company_website %>
</p>

<p>
  <strong>Company description:</strong>
  <%= @job.company_description %>
</p>

<p>
  <strong>Compensation range:</strong>
  <%= @job.compensation_range %>
</p>

<p>
  <strong>Remote:</strong>
  <%= @job.remote %>
</p>

<p>
  <strong>Years of experience:</strong>
  <%= @job.years_of_experience %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white">
    <%= render "shared/flash_notice" %>
    <%= render "shared/header" %>

    <main class="px-4 lg:px-10">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/layouts/simple_discussion.html.erb
<div class="row col-md-12">
  <h1>
    <%= t('community') %>
  </h1>
</div>

<div class="row simple_discussion">
  <div class="col-md-3 mb-3">

    <div class="card card-body">
      <%= link_to t('ask_a_question'), simple_discussion.new_forum_thread_path, class: "btn btn-outline-primary btn-block" %>
      <hr />

      <div class="forum-thread-filters">
        <h5>
          <strong>
            <%= t('filters') %>
          </strong>
        </h5>
        <div>
          <%= forum_link_to simple_discussion.forum_threads_path, exact: true do %>
            <%= icon "fa-fw fas", "bars" %>
            <%= t('.all_threads') %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div>
            <%= forum_link_to simple_discussion.mine_forum_threads_path do %><%= icon "fa-fw far", "user-circle" %>
              <%= t('.my_questions') %>
            <% end %>
          </div>
          <div>
            <%= forum_link_to simple_discussion.participating_forum_threads_path do %>
              <%= icon "fa-fw far", "comments" %>
              <%= t('.participating') %>
            <% end %>
          </div>
        <% end %>
        <div>
          <%= forum_link_to simple_discussion.answered_forum_threads_path do %>
            <%= icon "fa-fw fas", "check" %>
            <%= t('.answered') %>
          <% end %>
        </div>
        <div>
          <%= forum_link_to simple_discussion.unanswered_forum_threads_path do %>
            <%= icon "fa-fw fas", "question" %>
            <%= t('.unanswered') %>
          <% end %>
        </div>
      </div>

      <hr />

      <div class="forum-thread-filters">
        <h6>
          <strong>
            <%= t('.by_category') %>
          </strong>
        </h6>
        <div><%= forum_link_to simple_discussion.forum_threads_path, exact: true do %><%= icon "fa-fw fas", "circle" %> All<% end %></div>
        <% ForumCategory.sorted.each do |category| %>
          <div>
            <%= forum_link_to simple_discussion.forum_category_forum_threads_path(category) do %>
              <%= icon "fa-fw fas", "circle", style: "color: #{category.color}" %>
              <%= category.name %>
            <% end %>
          </div>
        <% end %>
      </div>

      <% if @forum_thread.present? && @forum_thread.persisted? %>
        <hr />

        <%# User has not posted in the thread or subscribed %>
        <h5><%= t('.notifications') %></h5>

        <%= link_to simple_discussion.forum_thread_notifications_path(@forum_thread), method: :post, class: "btn btn-secondary btn-sm btn-block mb-2" do %>
          <% if @forum_thread.subscribed? current_user %>
            <%= icon "fa-fw fas", "bell-slash" %> <%= t('.unsubscribe') %>
          <% else %>
            <%= icon "fa-fw fas", "bell" %>
            <%= t('.suscribe') %>
          <% end %>
        <% end %>

        <small><%= @forum_thread.subscribed_reason(current_user) %></small>
      <% end %>
    </div>

  </div>

  <div class="col-md-9 mb-3">

    <div class="card card-body">
      <%= yield %>
    </div>

  </div>
</div>

<% parent_layout("application") %>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    railsdevs
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="flex flex-wrap items-center justify-between px-3 py-3 text-gray-700 bg-gray-100 lg:px-10">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to "railsdevs", root_path, class:"link text-xl tracking-tight font-black" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border border-gray-500 rounded text-grey hover:text-gray-600 hover:border-gray-600">
        <svg class="w-3 h-3 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
      <div class="lg:flex-grow">
        <%= link_to "Jobs", jobs_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
      </div>
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <% if user_signed_in? %>
          <%= link_to "Edit account", edit_user_registration_path, class: "btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mb-0 block" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_spacer.html.erb
<hr/>

app/views/simple_discussion/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post],
  url: (@forum_post.persisted? ? simple_discussion.forum_thread_forum_post_path(@forum_thread, @forum_post) : simple_discussion.forum_thread_forum_posts_path(@forum_thread)),
  html: { data: { behavior: "comment-form" } } do |f| %>

  <% if @forum_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_post.errors.count, "error") %> prohibited this forum_post from being saved:</h2>

      <ul>
        <% @forum_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_area :body, placeholder: t('add_a_comment'), rows: 8, class: "form-control simplemde", data: { behavior: "comment-body" } %>
  </div>

  <div class="text-right">
    <div class="pull-left">
      <small>
        <%# Describe text formatting options here with a link %>
        <%#= link_to "Parsed with Markdown", "https://guides.github.com/features/mastering-markdown/", target: "_blank" %>
      </small>
    </div>

    <%= f.button "#{f.object.new_record? ? t('comment') : t('update_comment')  }", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('saving_comment')}"} %>
  </div>

<% end %>

app/views/simple_discussion/forum_posts/_forum_post.html.erb
<%# We don't currently cache the forum posts because they have permissions to deal with %>

<%= content_tag :div, id: dom_id(forum_post), class: forum_post_classes(forum_post) do %>
  <div class="card-header">

    <% if is_moderator_or_owner?(forum_post) %>
      <div class="float-right">
        <%= link_to icon("fas","edit"), simple_discussion.edit_forum_thread_forum_post_path(@forum_thread, forum_post),
          class: "text-muted",
          data: { toggle: "tooltip", placement: "left" },
          title: t('edit_this_post')
        %>
        &nbsp;
        <%= link_to icon("fas","trash"), simple_discussion.forum_thread_forum_post_path(@forum_thread, forum_post),
          class: "text-muted",
          method: :delete, 
          data: { toggle: "tooltip", placement: "left", confirm: "Are you sure you want to delete this post?" },
          title: t('edit_this_post')
        %>
      </div>
    <% end %>

    <div>
      <%= avatar_tag(forum_post.user.email) %>

      <strong class="forum-post-user">
        <%= forum_post.user.name %> <%= forum_user_badge(forum_post.user) %>
      </strong>
      <small>
        <%= t('commented_on') %>
        <%= link_to forum_post.created_at.strftime("%b %d, %Y"), simple_discussion.forum_thread_path(@forum_thread, anchor: "forum_post_#{forum_post.id}") %>:
      </small>
    </div>
  </div>

  <div class="card-body">
    <%= formatted_content forum_post.body %>
  </div>

  <% if @forum_thread.solved? && forum_post.solved? %>
    <div class="card-footer">
      <div class="pull-right">
        <strong class="text-success"><%= icon("fas","check") %> <%= t('solved') %></strong>

        <% if is_moderator_or_owner?(@forum_thread) %>
          <small>
            <%= link_to t('undo'), simple_discussion.unsolved_forum_thread_forum_post_path(@forum_thread, forum_post), method: :put %>
          </small>
        <% end %>
      </div>
    </div>

  <% elsif is_moderator_or_owner?(@forum_thread) %>
    <div class="card-footer">
      <div class="pull-right">
        <small>
          <%= link_to simple_discussion.solved_forum_thread_forum_post_path(@forum_thread, forum_post), method: :put do %>
            <%= icon("fas","fas","check") %>
            <%= t('this_solved_my_question') %>
          <% end %>
        </small>
      </div>
    </div>
  <% end %>
<% end %>

app/views/simple_discussion/forum_posts/edit.html.erb
<p><small><%= link_to "← Back to the thread", simple_discussion.forum_thread_path(@forum_thread) %></small></p>

<h2><%= content_tag :span, "Pinned", class: "text-muted" if @forum_thread.pinned? %> <%= @forum_thread.title %></h2>

<p class="thread-details">
  <strong><%= category_link(@forum_thread.forum_category) %></strong>
  • <%= t('asked_time_ago', time: time_ago_in_words(@forum_thread.created_at), author: @forum_thread.user.name) %>
</p>
</p>

<br />

<%= content_tag :div, id: dom_id(@forum_post), class: forum_post_classes(@forum_post) do %>
  <div class="card-header">
    <div>
      <%= avatar_tag(@forum_post.user.email) %>
      <strong class="forum-post-user"><%= @forum_post.user.name %></strong>
      <small>
        <%= t('commented_on')%>
        <%= link_to @forum_post.created_at.strftime("%b %d, %Y"), simple_discussion.forum_thread_url(@forum_thread, anchor: "forum_post_#{@forum_post.id}") %>:
      </small>
    </div>
  </div>

  <div class="card-body">
    <%= render "form" %>
  </div>
<% end %>

app/views/simple_discussion/forum_threads/_form.html.erb
<%= form_for @forum_thread,
   url: (@forum_thread.persisted? ? simple_discussion.forum_thread_path(@forum_thread) : simple_discussion.forum_threads_path),
   html: { data: {behavior: "comment-form"} } do |f| %>

  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_thread.errors.count, "error") %> prohibited this forum_thread from being saved:</h2>

      <ul>
      <% @forum_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :forum_category_id, t('choose_a_category') %>
    <%= f.collection_select :forum_category_id, ForumCategory.sorted, :id, :name, {include_blank: t('pick_a_category')}, {autofocus: true, class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label t('title') %>
    <%= f.text_field :title, placeholder: t('how_do_i'), class: "form-control" %>
  </div>

  <% if local_assigns.fetch(:posts, true) %>
    <%= f.fields_for :forum_posts do |p| %>
      <div class="form-group">
        <%= p.label :body, t('what_help_needed') %>
        <%= p.text_area :body, placeholder: t('add_a_comment'), rows: 10, class: "form-control simplemde", data: { behavior: "comment-body" } %>
      </div>
    <% end %>
  <% end %>

  <div class="form-group text-right">
    <% if f.object.new_record? %>
      <%= f.button t('ask_your_question'), class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('saving')}"} %>
    <% else %>
      <%= f.button "Update Thread", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('saving')}"} %>
    <% end %>
  </div>

<% end %>

app/views/simple_discussion/forum_threads/edit.html.erb
<%= content_for :title, "Edit Thread" %>

<h1><%= t('edit_thread') %></h1>

<div class="forum_post">
  <%= render 'form', posts: false %>
</div>

app/views/simple_discussion/forum_threads/index.html.erb
<% if @forum_threads.none? %>

    <div><%= t('search_not_found') %>. <%= t('check_out') %> <%= link_to t('latest_questions'), simple_discussion.forum_threads_path %> <%= t('instead') %> </div>

<% else %>

    <%= render partial: "simple_discussion/forum_threads/forum_thread", collection: @forum_threads, spacer_template: "shared/spacer" %>

  <div class="forum-threads-nav text-center">
    <%= will_paginate @forum_threads, url_builder: simple_discussion, renderer: SimpleDiscussion::BootstrapLinkRenderer %>
  </div>

<% end %>

app/views/simple_discussion/forum_threads/new.html.erb
<h1><%= t('start_a_discussion') %></h1>

<div class="forum_post">
  <%= render 'form' %>
</div>